import { homedir } from 'os';
import { join } from 'path';
import { ToolConfig, ToolName } from '../types.js';

export const AGENTS_SKILLS_DIR = '.agents/skills';

const home = homedir();
const xdgConfig = process.env.XDG_CONFIG_HOME || join(home, '.config');
const codexHome = process.env.CODEX_HOME?.trim() || join(home, '.codex');
const claudeHome = process.env.CLAUDE_CONFIG_DIR?.trim() || join(home, '.claude');

export const TOOL_CONFIGS: Record<ToolName, ToolConfig> = {
  'claude-code': {
    name: 'claude-code',
    displayName: 'Claude Code',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(claudeHome, 'skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.claude/skills',
    showInList: true,
  },
  'codex': {
    name: 'codex',
    displayName: 'Codex',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(codexHome, 'skills'),
    supportsLink: true,
    native: true,
    showInList: true,
  },
  'cursor': {
    name: 'cursor',
    displayName: 'Cursor',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.cursor/skills'),
    supportsLink: true,
    native: true,
    showInList: true,
  },
  'openclaw': {
    name: 'openclaw',
    displayName: 'OpenClaw',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.openclaw/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: 'skills',
    showInList: true,
  },
  'opencode': {
    name: 'opencode',
    displayName: 'OpenCode',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'opencode/skills'),
    supportsLink: true,
    native: true,
    showInList: true,
  },
  'gemini-cli': {
    name: 'gemini-cli',
    displayName: 'Gemini CLI',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.gemini/skills'),
    supportsLink: true,
    native: true,
    showInList: true,
  },
  'github-copilot': {
    name: 'github-copilot',
    displayName: 'GitHub Copilot',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.copilot/skills'),
    supportsLink: true,
    native: true,
    showInList: true,
  },
  'cline': {
    name: 'cline',
    displayName: 'Cline',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.agents/skills'),
    supportsLink: true,
    native: true,
    showInList: true,
  },
  'kilo': {
    name: 'kilo',
    displayName: 'Kilo Code',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.kilocode/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.kilocode/skills',
    showInList: true,
  },
  'roo': {
    name: 'roo',
    displayName: 'Roo Code',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.roo/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.roo/skills',
    showInList: true,
  },
  'kiro-cli': {
    name: 'kiro-cli',
    displayName: 'Kiro CLI',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.kiro/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.kiro/skills',
    showInList: true,
  },
  'trae': {
    name: 'trae',
    displayName: 'Trae',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.trae/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.trae/skills',
    showInList: true,
  },
  'trae-cn': {
    name: 'trae-cn',
    displayName: 'Trae CN',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.trae-cn/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.trae/skills',
    showInList: true,
  },
  'codebuddy': {
    name: 'codebuddy',
    displayName: 'CodeBuddy',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.codebuddy/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.codebuddy/skills',
    showInList: true,
  },
  'windsurf': {
    name: 'windsurf',
    displayName: 'Windsurf',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.codeium/windsurf/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.windsurf/skills',
    showInList: true,
  },
  'goose': {
    name: 'goose',
    displayName: 'Goose',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'goose/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.goose/skills',
    showInList: true,
  },
  'adal': {
    name: 'adal',
    displayName: 'AdaL',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.adal/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.adal/skills',
    showInList: false,
  },
  'amp': {
    name: 'amp',
    displayName: 'Amp',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'agents/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'antigravity': {
    name: 'antigravity',
    displayName: 'Antigravity',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.gemini/antigravity/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'augment': {
    name: 'augment',
    displayName: 'Augment',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.augment/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.augment/skills',
    showInList: false,
  },
  'command-code': {
    name: 'command-code',
    displayName: 'Command Code',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.commandcode/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.commandcode/skills',
    showInList: false,
  },
  'continue': {
    name: 'continue',
    displayName: 'Continue',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.continue/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.continue/skills',
    showInList: false,
  },
  'cortex': {
    name: 'cortex',
    displayName: 'Cortex Code',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.snowflake/cortex/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.cortex/skills',
    showInList: false,
  },
  'crush': {
    name: 'crush',
    displayName: 'Crush',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'crush/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.crush/skills',
    showInList: false,
  },
  'deepagents': {
    name: 'deepagents',
    displayName: 'Deep Agents',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.deepagents/agent/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'droid': {
    name: 'droid',
    displayName: 'Droid',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.factory/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.factory/skills',
    showInList: false,
  },
  'firebender': {
    name: 'firebender',
    displayName: 'Firebender',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.firebender/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'iflow-cli': {
    name: 'iflow-cli',
    displayName: 'iFlow CLI',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.iflow/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.iflow/skills',
    showInList: false,
  },
  'junie': {
    name: 'junie',
    displayName: 'Junie',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.junie/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.junie/skills',
    showInList: false,
  },
  'kimi-cli': {
    name: 'kimi-cli',
    displayName: 'Kimi Code CLI',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'agents/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'kode': {
    name: 'kode',
    displayName: 'Kode',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.kode/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.kode/skills',
    showInList: false,
  },
  'mcpjam': {
    name: 'mcpjam',
    displayName: 'MCPJam',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.mcpjam/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.mcpjam/skills',
    showInList: false,
  },
  'mistral-vibe': {
    name: 'mistral-vibe',
    displayName: 'Mistral Vibe',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.vibe/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.vibe/skills',
    showInList: false,
  },
  'mux': {
    name: 'mux',
    displayName: 'Mux',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.mux/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.mux/skills',
    showInList: false,
  },
  'neovate': {
    name: 'neovate',
    displayName: 'Neovate',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.neovate/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.neovate/skills',
    showInList: false,
  },
  'openhands': {
    name: 'openhands',
    displayName: 'OpenHands',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.openhands/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.openhands/skills',
    showInList: false,
  },
  'pi': {
    name: 'pi',
    displayName: 'Pi',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.pi/agent/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.pi/skills',
    showInList: false,
  },
  'pochi': {
    name: 'pochi',
    displayName: 'Pochi',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.pochi/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.pochi/skills',
    showInList: false,
  },
  'qoder': {
    name: 'qoder',
    displayName: 'Qoder',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.qoder/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.qoder/skills',
    showInList: false,
  },
  'qwen-code': {
    name: 'qwen-code',
    displayName: 'Qwen Code',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.qwen/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.qwen/skills',
    showInList: false,
  },
  'replit': {
    name: 'replit',
    displayName: 'Replit',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'agents/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'universal': {
    name: 'universal',
    displayName: 'Universal',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(xdgConfig, 'agents/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'warp': {
    name: 'warp',
    displayName: 'Warp',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.agents/skills'),
    supportsLink: true,
    native: true,
    showInList: false,
  },
  'zencoder': {
    name: 'zencoder',
    displayName: 'Zencoder',
    skillsDir: AGENTS_SKILLS_DIR,
    globalSkillsDir: join(home, '.zencoder/skills'),
    supportsLink: true,
    native: false,
    symlinkDir: '.zencoder/skills',
    showInList: false,
  },
};

export function getToolConfig(name: string): ToolConfig | undefined {
  return TOOL_CONFIGS[name as ToolName];
}

export function getTargetDir(): string {
  return AGENTS_SKILLS_DIR;
}
